services:
  gateway:
    build:
      context: ../gateway
      dockerfile: Dockerfile
    container_name: live-gateway
    ports:
      - '8080:8080'
    volumes:
      - ./srs/html:/app/runtime/srs-html:ro
    depends_on:
      - srs
    restart: unless-stopped

  srs:
    image: ossrs/srs:5
    container_name: live-srs
    command: ['./objs/srs', '-c', 'conf/srs.conf']
    ports:
      - '1935:1935'
      - '8088:8088'
    volumes:
      - ./srs/srs.conf:/usr/local/srs/conf/srs.conf:ro
      - ./srs/html:/usr/local/srs/objs/nginx/html
    restart: unless-stopped
